// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/notes_api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpsertRequest struct {
	Files                []*UpsertRequest_Files `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpsertRequest) Reset()         { *m = UpsertRequest{} }
func (m *UpsertRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertRequest) ProtoMessage()    {}
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{0}
}

func (m *UpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRequest.Unmarshal(m, b)
}
func (m *UpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRequest.Marshal(b, m, deterministic)
}
func (m *UpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRequest.Merge(m, src)
}
func (m *UpsertRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertRequest.Size(m)
}
func (m *UpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRequest proto.InternalMessageInfo

func (m *UpsertRequest) GetFiles() []*UpsertRequest_Files {
	if m != nil {
		return m.Files
	}
	return nil
}

type UpsertRequest_Files struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertRequest_Files) Reset()         { *m = UpsertRequest_Files{} }
func (m *UpsertRequest_Files) String() string { return proto.CompactTextString(m) }
func (*UpsertRequest_Files) ProtoMessage()    {}
func (*UpsertRequest_Files) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{0, 0}
}

func (m *UpsertRequest_Files) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertRequest_Files.Unmarshal(m, b)
}
func (m *UpsertRequest_Files) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertRequest_Files.Marshal(b, m, deterministic)
}
func (m *UpsertRequest_Files) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertRequest_Files.Merge(m, src)
}
func (m *UpsertRequest_Files) XXX_Size() int {
	return xxx_messageInfo_UpsertRequest_Files.Size(m)
}
func (m *UpsertRequest_Files) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertRequest_Files.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertRequest_Files proto.InternalMessageInfo

func (m *UpsertRequest_Files) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *UpsertRequest_Files) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpsertResponse struct {
	Files                []*UpsertResponse_Files `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpsertResponse) Reset()         { *m = UpsertResponse{} }
func (m *UpsertResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertResponse) ProtoMessage()    {}
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{1}
}

func (m *UpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertResponse.Unmarshal(m, b)
}
func (m *UpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertResponse.Marshal(b, m, deterministic)
}
func (m *UpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertResponse.Merge(m, src)
}
func (m *UpsertResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertResponse.Size(m)
}
func (m *UpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertResponse proto.InternalMessageInfo

func (m *UpsertResponse) GetFiles() []*UpsertResponse_Files {
	if m != nil {
		return m.Files
	}
	return nil
}

type UpsertResponse_Files struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpsertResponse_Files) Reset()         { *m = UpsertResponse_Files{} }
func (m *UpsertResponse_Files) String() string { return proto.CompactTextString(m) }
func (*UpsertResponse_Files) ProtoMessage()    {}
func (*UpsertResponse_Files) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{1, 0}
}

func (m *UpsertResponse_Files) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertResponse_Files.Unmarshal(m, b)
}
func (m *UpsertResponse_Files) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertResponse_Files.Marshal(b, m, deterministic)
}
func (m *UpsertResponse_Files) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertResponse_Files.Merge(m, src)
}
func (m *UpsertResponse_Files) XXX_Size() int {
	return xxx_messageInfo_UpsertResponse_Files.Size(m)
}
func (m *UpsertResponse_Files) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertResponse_Files.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertResponse_Files proto.InternalMessageInfo

func (m *UpsertResponse_Files) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpsertResponse_Files) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UpsertResponse_Files) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ReadRequest struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{2}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type ReadResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff16eb62a4823ab, []int{3}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ReadResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ReadResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*UpsertRequest)(nil), "UpsertRequest")
	proto.RegisterType((*UpsertRequest_Files)(nil), "UpsertRequest.Files")
	proto.RegisterType((*UpsertResponse)(nil), "UpsertResponse")
	proto.RegisterType((*UpsertResponse_Files)(nil), "UpsertResponse.Files")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
}

func init() {
	proto.RegisterFile("api/notes_api.proto", fileDescriptor_4ff16eb62a4823ab)
}

var fileDescriptor_4ff16eb62a4823ab = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0x17, 0x67, 0xe7, 0xf6, 0xf6, 0x47, 0x88, 0x0a, 0xa5, 0x20, 0x8c, 0x80, 0x30, 0x1d,
	0x64, 0x30, 0x8f, 0xe2, 0x61, 0x1e, 0x3c, 0x7a, 0x28, 0x78, 0xd1, 0x43, 0x79, 0xda, 0x37, 0x09,
	0xb8, 0x36, 0x36, 0xd9, 0xc5, 0x0f, 0xe3, 0x67, 0x95, 0xb4, 0x8d, 0x34, 0x1e, 0xbc, 0x79, 0x7c,
	0xef, 0xf7, 0xc8, 0xef, 0xfd, 0x09, 0x9c, 0xa0, 0x56, 0xab, 0xa2, 0xb4, 0x64, 0x32, 0xd4, 0x4a,
	0xea, 0xaa, 0xb4, 0xa5, 0xf8, 0x84, 0xe9, 0xa3, 0x36, 0x54, 0xd9, 0x94, 0x3e, 0xf6, 0x64, 0x2c,
	0xbf, 0x82, 0x68, 0xab, 0xde, 0xc9, 0xc4, 0x6c, 0xde, 0x5f, 0x8c, 0xd7, 0xa7, 0x32, 0xc0, 0xf2,
	0xde, 0xb1, 0xb4, 0x29, 0x49, 0x6e, 0x21, 0xaa, 0x63, 0x9e, 0xc0, 0xd0, 0x65, 0x0a, 0xdc, 0x51,
	0xcc, 0xe6, 0x6c, 0x31, 0x4a, 0x7f, 0x62, 0x1e, 0xc3, 0xd1, 0x8e, 0x8c, 0xc1, 0x37, 0x8a, 0x0f,
	0x6a, 0xe4, 0x43, 0xf1, 0xc5, 0x60, 0xe6, 0x5f, 0x37, 0xba, 0x2c, 0x0c, 0xf1, 0x65, 0x68, 0x3f,
	0x93, 0x21, 0x0f, 0xf5, 0x99, 0xd7, 0x77, 0x14, 0x2c, 0x50, 0xf0, 0x73, 0x80, 0xd7, 0x8a, 0xd0,
	0x52, 0x9e, 0xa1, 0x6d, 0xfd, 0xa3, 0x36, 0xb3, 0xb1, 0x0e, 0xef, 0x75, 0xee, 0x71, 0xbf, 0xc1,
	0x6d, 0x66, 0x63, 0xc5, 0x25, 0x8c, 0x53, 0xc2, 0xdc, 0xaf, 0xe6, 0x8f, 0x29, 0xc5, 0x16, 0x26,
	0x4d, 0x69, 0x3b, 0xc8, 0x3f, 0xb5, 0xb4, 0x7e, 0x86, 0xe8, 0xc1, 0x9d, 0x90, 0x2f, 0x61, 0xd0,
	0xec, 0x86, 0xcf, 0xc2, 0x13, 0x25, 0xc7, 0xbf, 0x96, 0x26, 0x7a, 0xfc, 0x02, 0x0e, 0x5d, 0x77,
	0x7c, 0x22, 0x3b, 0xf3, 0x24, 0x53, 0xd9, 0x6d, 0x59, 0xf4, 0xee, 0xe0, 0x69, 0xb8, 0x42, 0xad,
	0x6e, 0x50, 0xab, 0x97, 0x41, 0xfd, 0x3f, 0xae, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xcd,
	0x18, 0xfc, 0x36, 0x02, 0x00, 0x00,
}
